/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -i ../dbus-ping-cmdline.ggo -F dbus-ping-cmdline --default-optional --show-required --unamed-opts=CONTENTS

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "dbus-ping-cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [CONTENTS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -v, --verbose                 Inrease program output verbosity",
  "      --bash                    Print result as bash variables",
  "\n Group: Connection",
  "      --session                 send to the session message bus",
  "      --system                  send to the system message bus",
  "  -a, --address=ADDRESS         specify the address of the message bus",
  "\nMessage:",
  "  -t, --type=STRING             message type  (possible values=\"method_call\", \n                                  \"signal\" default=`method_call')",
  "  -d, --destination=BUS_NAME    bus name of the destination",
  "  -p, --path=OBJECT_PATH        target object's path (mandatory)",
  "  -i, --interface=NAME          interface of the target object",
  "  -m, --member=NAME             member of the target object (mandatory)",
  "  -x, --contents-multiply=COUNT append message contents clone  (default=`0')",
  "\nSend:",
  "  -c, --count=LONGLONG          number of times the message will be sent  \n                                  (default=`1')",
  "      --clone                   intensively rebuild the message before sending \n                                  (default is copy)",
  "      --reply-timeout=MSEC      reply message timeout  (default=`-1')",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_LONGLONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_type_values[] = {"method_call", "signal", 0}; /*< Possible values for type. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->bash_given = 0 ;
  args_info->session_given = 0 ;
  args_info->system_given = 0 ;
  args_info->address_given = 0 ;
  args_info->type_given = 0 ;
  args_info->destination_given = 0 ;
  args_info->path_given = 0 ;
  args_info->interface_given = 0 ;
  args_info->member_given = 0 ;
  args_info->contents_multiply_given = 0 ;
  args_info->count_given = 0 ;
  args_info->clone_given = 0 ;
  args_info->reply_timeout_given = 0 ;
  args_info->Connection_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->address_arg = NULL;
  args_info->address_orig = NULL;
  args_info->type_arg = gengetopt_strdup ("method_call");
  args_info->type_orig = NULL;
  args_info->destination_arg = NULL;
  args_info->destination_orig = NULL;
  args_info->path_arg = NULL;
  args_info->path_orig = NULL;
  args_info->interface_arg = NULL;
  args_info->interface_orig = NULL;
  args_info->member_arg = NULL;
  args_info->member_orig = NULL;
  args_info->contents_multiply_arg = 0;
  args_info->contents_multiply_orig = NULL;
  args_info->count_arg = 1;
  args_info->count_orig = NULL;
  args_info->reply_timeout_arg = -1;
  args_info->reply_timeout_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->verbose_help = gengetopt_args_info_help[2] ;
  args_info->bash_help = gengetopt_args_info_help[3] ;
  args_info->session_help = gengetopt_args_info_help[5] ;
  args_info->system_help = gengetopt_args_info_help[6] ;
  args_info->address_help = gengetopt_args_info_help[7] ;
  args_info->type_help = gengetopt_args_info_help[9] ;
  args_info->destination_help = gengetopt_args_info_help[10] ;
  args_info->path_help = gengetopt_args_info_help[11] ;
  args_info->interface_help = gengetopt_args_info_help[12] ;
  args_info->member_help = gengetopt_args_info_help[13] ;
  args_info->contents_multiply_help = gengetopt_args_info_help[14] ;
  args_info->count_help = gengetopt_args_info_help[16] ;
  args_info->clone_help = gengetopt_args_info_help[17] ;
  args_info->reply_timeout_help = gengetopt_args_info_help[18] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->address_arg));
  free_string_field (&(args_info->address_orig));
  free_string_field (&(args_info->type_arg));
  free_string_field (&(args_info->type_orig));
  free_string_field (&(args_info->destination_arg));
  free_string_field (&(args_info->destination_orig));
  free_string_field (&(args_info->path_arg));
  free_string_field (&(args_info->path_orig));
  free_string_field (&(args_info->interface_arg));
  free_string_field (&(args_info->interface_orig));
  free_string_field (&(args_info->member_arg));
  free_string_field (&(args_info->member_orig));
  free_string_field (&(args_info->contents_multiply_orig));
  free_string_field (&(args_info->count_orig));
  free_string_field (&(args_info->reply_timeout_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->bash_given)
    write_into_file(outfile, "bash", 0, 0 );
  if (args_info->session_given)
    write_into_file(outfile, "session", 0, 0 );
  if (args_info->system_given)
    write_into_file(outfile, "system", 0, 0 );
  if (args_info->address_given)
    write_into_file(outfile, "address", args_info->address_orig, 0);
  if (args_info->type_given)
    write_into_file(outfile, "type", args_info->type_orig, cmdline_parser_type_values);
  if (args_info->destination_given)
    write_into_file(outfile, "destination", args_info->destination_orig, 0);
  if (args_info->path_given)
    write_into_file(outfile, "path", args_info->path_orig, 0);
  if (args_info->interface_given)
    write_into_file(outfile, "interface", args_info->interface_orig, 0);
  if (args_info->member_given)
    write_into_file(outfile, "member", args_info->member_orig, 0);
  if (args_info->contents_multiply_given)
    write_into_file(outfile, "contents-multiply", args_info->contents_multiply_orig, 0);
  if (args_info->count_given)
    write_into_file(outfile, "count", args_info->count_orig, 0);
  if (args_info->clone_given)
    write_into_file(outfile, "clone", 0, 0 );
  if (args_info->reply_timeout_given)
    write_into_file(outfile, "reply-timeout", args_info->reply_timeout_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_Connection(struct gengetopt_args_info *args_info)
{
  if (! args_info->Connection_group_counter)
    return;
  
  args_info->session_given = 0 ;
  args_info->system_given = 0 ;
  args_info->address_given = 0 ;
  free_string_field (&(args_info->address_arg));
  free_string_field (&(args_info->address_orig));

  args_info->Connection_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->path_given)
    {
      fprintf (stderr, "%s: '--path' ('-p') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (! args_info->member_given)
    {
      fprintf (stderr, "%s: '--member' ('-m') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONGLONG:
#ifdef HAVE_LONG_LONG
    if (val) *((long long int*)field) = (long long int) strtol (val, &stop_char, 0);
#else
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
#endif
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONGLONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "verbose",	0, NULL, 'v' },
        { "bash",	0, NULL, 0 },
        { "session",	0, NULL, 0 },
        { "system",	0, NULL, 0 },
        { "address",	1, NULL, 'a' },
        { "type",	1, NULL, 't' },
        { "destination",	1, NULL, 'd' },
        { "path",	1, NULL, 'p' },
        { "interface",	1, NULL, 'i' },
        { "member",	1, NULL, 'm' },
        { "contents-multiply",	1, NULL, 'x' },
        { "count",	1, NULL, 'c' },
        { "clone",	0, NULL, 0 },
        { "reply-timeout",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVva:t:d:p:i:m:x:c:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'v':	/* Inrease program output verbosity.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* specify the address of the message bus.  */
        
          if (args_info->Connection_group_counter && override)
            reset_group_Connection (args_info);
          args_info->Connection_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->address_arg), 
               &(args_info->address_orig), &(args_info->address_given),
              &(local_args_info.address_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "address", 'a',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* message type.  */
        
        
          if (update_arg( (void *)&(args_info->type_arg), 
               &(args_info->type_orig), &(args_info->type_given),
              &(local_args_info.type_given), optarg, cmdline_parser_type_values, "method_call", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "type", 't',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* bus name of the destination.  */
        
        
          if (update_arg( (void *)&(args_info->destination_arg), 
               &(args_info->destination_orig), &(args_info->destination_given),
              &(local_args_info.destination_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "destination", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* target object's path.  */
        
        
          if (update_arg( (void *)&(args_info->path_arg), 
               &(args_info->path_orig), &(args_info->path_given),
              &(local_args_info.path_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "path", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* interface of the target object.  */
        
        
          if (update_arg( (void *)&(args_info->interface_arg), 
               &(args_info->interface_orig), &(args_info->interface_given),
              &(local_args_info.interface_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "interface", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* member of the target object.  */
        
        
          if (update_arg( (void *)&(args_info->member_arg), 
               &(args_info->member_orig), &(args_info->member_given),
              &(local_args_info.member_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "member", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* append message contents clone.  */
        
        
          if (update_arg( (void *)&(args_info->contents_multiply_arg), 
               &(args_info->contents_multiply_orig), &(args_info->contents_multiply_given),
              &(local_args_info.contents_multiply_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "contents-multiply", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* number of times the message will be sent.  */
        
        
          if (update_arg( (void *)&(args_info->count_arg), 
               &(args_info->count_orig), &(args_info->count_given),
              &(local_args_info.count_given), optarg, 0, "1", ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "count", 'c',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Print result as bash variables.  */
          if (strcmp (long_options[option_index].name, "bash") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->bash_given),
                &(local_args_info.bash_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "bash", '-',
                additional_error))
              goto failure;
          
          }
          /* send to the session message bus.  */
          else if (strcmp (long_options[option_index].name, "session") == 0)
          {
          
            if (args_info->Connection_group_counter && override)
              reset_group_Connection (args_info);
            args_info->Connection_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->session_given),
                &(local_args_info.session_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "session", '-',
                additional_error))
              goto failure;
          
          }
          /* send to the system message bus.  */
          else if (strcmp (long_options[option_index].name, "system") == 0)
          {
          
            if (args_info->Connection_group_counter && override)
              reset_group_Connection (args_info);
            args_info->Connection_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->system_given),
                &(local_args_info.system_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "system", '-',
                additional_error))
              goto failure;
          
          }
          /* intensively rebuild the message before sending (default is copy).  */
          else if (strcmp (long_options[option_index].name, "clone") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->clone_given),
                &(local_args_info.clone_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "clone", '-',
                additional_error))
              goto failure;
          
          }
          /* reply message timeout.  */
          else if (strcmp (long_options[option_index].name, "reply-timeout") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->reply_timeout_arg), 
                 &(args_info->reply_timeout_orig), &(args_info->reply_timeout_given),
                &(local_args_info.reply_timeout_given), optarg, 0, "-1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "reply-timeout", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->Connection_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group Connection were given. At most one is required%s.\n", argv[0], args_info->Connection_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
